/// V2: out-of-fold predicted against observed pass rate, by decile of prediction.
table 'Overtaking Calibration'
	lineageTag: 40aa9fa8-035c-53fd-ba79-a99f6dedc426

	column Decile
		dataType: int64
		formatString: 0
		lineageTag: 3aca7ea6-946f-5f4d-b4e7-642fbece0b01
		summarizeBy: none
		sourceColumn: decile

		annotation SummarizationSetBy = User

	column Opportunities
		dataType: int64
		formatString: #,0
		lineageTag: 8fe68de1-7b2c-5ddd-bb88-651629841d15
		summarizeBy: none
		sourceColumn: opportunities

		annotation SummarizationSetBy = User

	column Predicted
		dataType: double
		formatString: 0.0%
		lineageTag: 5c21aaf7-6a41-5953-b203-9b4bd5c3276c
		summarizeBy: none
		sourceColumn: mean_predicted

		annotation SummarizationSetBy = User

	column Observed
		dataType: double
		formatString: 0.0%
		lineageTag: e77e974e-d79a-541a-b1e9-e44b9bce48b3
		summarizeBy: none
		sourceColumn: observed_rate

		annotation SummarizationSetBy = User

	partition 'Overtaking Calibration' = m
		mode: import
		source =
				let
				    Source = Csv.Document(PitWallFile("overtaking_reliability.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Blanks = Table.ReplaceValue(Promoted, "", null, Replacer.ReplaceValue, Table.ColumnNames(Promoted)),
				    Typed = Table.TransformColumnTypes(Blanks, {{"decile", Int64.Type}, {"opportunities", Int64.Type}, {"mean_predicted", type number}, {"observed_rate", type number}}, "en-US")
				in
				    Typed

	annotation PBI_ResultType = Table
