/// Fact: one row per car per race, the official classification.
table Result
	lineageTag: 6e2d1b83-0967-5ee8-8e12-e3bdf0a7c88a

	column 'Race ID'
		dataType: string
		isHidden
		lineageTag: ef4c2014-5fc1-51b6-8499-fc1f7f4eac46
		summarizeBy: none
		sourceColumn: race_id

		annotation SummarizationSetBy = User

	column 'Driver Code'
		dataType: string
		isHidden
		lineageTag: 658f5b23-2710-5c1b-b9a4-09ac0c6567e2
		summarizeBy: none
		sourceColumn: driver_code

		annotation SummarizationSetBy = User

	column Team
		dataType: string
		lineageTag: f167ec07-aa7d-5b24-9248-2bbdf2539d53
		summarizeBy: none
		sourceColumn: team

		annotation SummarizationSetBy = User

	column 'Grid Position'
		dataType: double
		formatString: 0
		lineageTag: 45692184-3382-5e16-899f-474aea5ea435
		summarizeBy: none
		sourceColumn: grid_position

		annotation SummarizationSetBy = User

	column 'Finish Position'
		dataType: double
		formatString: 0
		lineageTag: 8c210815-9b2f-508a-b2b6-452e762f2516
		summarizeBy: none
		sourceColumn: finish_position

		annotation SummarizationSetBy = User

	column Classified
		dataType: boolean
		lineageTag: d591d759-a73e-5b6b-8de2-ff39bfe80726
		summarizeBy: none
		sourceColumn: classified

		annotation SummarizationSetBy = User

	column Status
		dataType: string
		lineageTag: e3cc06ca-558c-5244-aade-728c7ddd1eda
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = User

	column Points
		dataType: double
		formatString: 0.#
		lineageTag: db6824e1-eed4-5866-ab5d-5620d757e807
		summarizeBy: none
		sourceColumn: points

		annotation SummarizationSetBy = User

	column 'Positions Gained'
		dataType: double
		formatString: 0
		lineageTag: 60b646c3-639f-59fb-b509-3d4c438e7ddc
		summarizeBy: none
		sourceColumn: positions_gained

		annotation SummarizationSetBy = User

	partition Result = m
		mode: import
		source =
				let
				    Source = Csv.Document(PitWallFile("fact_result.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Blanks = Table.ReplaceValue(Promoted, "", null, Replacer.ReplaceValue, Table.ColumnNames(Promoted)),
				    Typed = Table.TransformColumnTypes(Blanks, {{"race_id", type text}, {"driver_code", type text}, {"team", type text}, {"grid_position", type number}, {"finish_position", type number}, {"classified", type logical}, {"status", type text}, {"points", type number}, {"positions_gained", type number}}, "en-US")
				in
				    Typed

	annotation PBI_ResultType = Table
