/// Per circuit and compound rank: tyre wear (seconds lost per lap of tyre age) under each estimator.
table 'Tyre Wear Estimate'
	lineageTag: 9de43dc1-f855-5f42-b3a1-707230e600ed

	column 'Circuit Key'
		dataType: string
		isHidden
		lineageTag: 7a822426-6def-5868-948e-151d7c3da5ab
		summarizeBy: none
		sourceColumn: circuit_key

		annotation SummarizationSetBy = User

	column 'Compound Rank'
		dataType: string
		isHidden
		lineageTag: f29527c3-32af-5d1a-8be2-f560b77c5855
		summarizeBy: none
		sourceColumn: compound_rank

		annotation SummarizationSetBy = User

	column Estimator
		dataType: string
		lineageTag: 04f3aa03-e80c-5d98-b771-febd76de6d5b
		summarizeBy: none
		sourceColumn: estimator
		sortByColumn: 'Estimator Order'

		annotation SummarizationSetBy = User

	column 'Estimator Order'
		dataType: int64
		formatString: 0
		isHidden
		lineageTag: 63cba2bd-c2c6-587f-9018-467ffac625e6
		summarizeBy: none
		sourceColumn: estimator_order

		annotation SummarizationSetBy = User

	column 'Wear (s per lap)'
		dataType: double
		formatString: 0.000
		lineageTag: 7949f34c-16a4-5707-a55e-c77ae23fe42f
		summarizeBy: none
		sourceColumn: wear_s_per_lap

		annotation SummarizationSetBy = User

	column 'Standard Error (s per lap)'
		dataType: double
		formatString: 0.000
		lineageTag: 041d5139-7db3-5d03-8b23-cc8b541fd6b9
		summarizeBy: none
		sourceColumn: se_s_per_lap

		annotation SummarizationSetBy = User

	column Laps
		dataType: int64
		formatString: #,0
		lineageTag: b524e9e9-dbc9-5f87-8400-95f2d46f20c6
		summarizeBy: none
		sourceColumn: laps

		annotation SummarizationSetBy = User

	column Stints
		dataType: int64
		formatString: #,0
		lineageTag: 34b23217-0e90-5c25-b753-dd2741b8ce3a
		summarizeBy: none
		sourceColumn: stints

		annotation SummarizationSetBy = User

	column Races
		dataType: int64
		formatString: 0
		lineageTag: a29801bd-4b75-518b-960b-ae71f3123ec6
		summarizeBy: none
		sourceColumn: races

		annotation SummarizationSetBy = User

	partition 'Tyre Wear Estimate' = m
		mode: import
		source =
				let
				    Source = Csv.Document(PitWallFile("degradation.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Blanks = Table.ReplaceValue(Promoted, "", null, Replacer.ReplaceValue, Table.ColumnNames(Promoted)),
				    Typed = Table.TransformColumnTypes(Blanks, {{"circuit_key", type text}, {"compound_rank", type text}, {"estimator", type text}, {"estimator_order", Int64.Type}, {"wear_s_per_lap", type number}, {"se_s_per_lap", type number}, {"laps", Int64.Type}, {"stints", Int64.Type}, {"races", Int64.Type}}, "en-US")
				in
				    Typed

	annotation PBI_ResultType = Table
