/// Dimension: compound rank within an event (Pirelli labels are relative, so rank is the comparable unit).
table 'Tyre Compound'
	lineageTag: 22ce084b-79e2-5972-866b-0c8bcb6aefe0

	column 'Compound Rank'
		dataType: string
		lineageTag: 264ffd78-b230-5cd3-a217-fab3e2cd6ccc
		summarizeBy: none
		sourceColumn: compound_rank
		sortByColumn: 'Compound Order'

		annotation SummarizationSetBy = User

	column 'Compound Order'
		dataType: int64
		formatString: 0
		isHidden
		lineageTag: 64d20fa3-6ce1-5eaf-9fbe-b822fdafd944
		summarizeBy: none
		sourceColumn: compound_order

		annotation SummarizationSetBy = User

	partition 'Tyre Compound' = m
		mode: import
		source =
				let
				    Source = Csv.Document(PitWallFile("dim_compound.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Blanks = Table.ReplaceValue(Promoted, "", null, Replacer.ReplaceValue, Table.ColumnNames(Promoted)),
				    Typed = Table.TransformColumnTypes(Blanks, {{"compound_rank", type text}, {"compound_order", Int64.Type}}, "en-US")
				in
				    Typed

	annotation PBI_ResultType = Table
